"""The Data Agent: understands and analyzes the dataset.

Tools it can use: documentation RAG, SQL queries, Python analysis
(src/tools/data_tools.py). It never computes numbers itself.

Two ways to run:
    offline  - follows the rule-based Plan from router.py (deterministic)
    LLM      - Claude decides which tools to call, in what order, in a
               tool-use loop, and can combine them freely

Either way, every tool call and its evidence is recorded in the Trace, and
the DATA FACT statements are generated by code from the tool results.
"""

import json
from dataclasses import dataclass

from src.agents import facts
from src.agents.trace import CAVEAT, DATA_FACT, DOC_FACT, INFERENCE
from src.data.variables import DEFAULT_UNDERSERVED_INDICATORS, DERIVED_BY_NAME, GROUPING_COLUMNS
from src.llm import text_of
from src.outreach.profile import build_profile
from src.tools.data_tools import DATA_TOOLS, DATA_TOOLS_BY_NAME
from src.tools.registry import Tool, tool_result_text

AGENT = "Data Agent"
MAX_TURNS = 12


@dataclass
class DataReport:
    summary: str = ""                 # LLM-mode narrative (model-generated), empty offline
    population: object = None         # PopulationProfile for the Outreach Agent, if identified
    population_reason: str = ""


def tool(tool_name, trace, **arguments):
    """Call a tool by name, as the offline agent does."""
    result, error = DATA_TOOLS_BY_NAME[tool_name].run(trace, arguments)
    if error:
        trace.warn(f"{tool_name} failed: {result['error']}")
    return result


# ---------------------------------------------------------------------------
# Offline mode
# ---------------------------------------------------------------------------
def define_variables(names, trace):
    for name in names:
        result = tool("lookup_variable", trace, name=name)
        if result.get("found"):
            trace.say(DOC_FACT, f"Codebook: {result['codebook']}", [f"codebook:{name}"])
            if "not in the curated" not in result["data_dictionary"]:
                universe = [line for line in result["data_dictionary"].splitlines() if "Universe" in line]
                if universe:
                    trace.say(DOC_FACT, f"Data dictionary ({name}): {universe[0].lstrip('- ')}",
                              ["documents/data_dictionary.md"])
        else:
            trace.say(CAVEAT, result["message"])


def outcome_sources(outcome):
    if "indicator" in outcome:
        return list(DERIVED_BY_NAME[outcome["indicator"]].sources)
    return [outcome["variable"]]


def run_offline(plan, question, trace, context_population=None, wants_profile=False):
    trace.step(AGENT, "decided", detail="offline plan: " + " | ".join(plan.reasons))
    report = DataReport()

    if plan.intent == "documentation":
        if plan.variables_mentioned:
            define_variables(plan.variables_mentioned, trace)
        else:
            result = tool("search_documentation", trace, query=question, k=6)
            codebook_hits = [r for r in result["results"] if r["source"] == "codebook"]
            other_hits = [r for r in result["results"] if r["source"] != "codebook"]
            if codebook_hits:
                trace.say(DOC_FACT, "Codebook variables retrieved for this question: " + "; ".join(
                    r["title"] for r in codebook_hits), [r["id"] for r in codebook_hits])
            for hit in other_hits[:3]:
                trace.say(DOC_FACT, f"{hit['title']}: {hit['text'][:600]}", [hit["id"]])
            trace.say(INFERENCE, "These documents were selected by retrieval similarity to the question; "
                                 "check the definitions before relying on them.")
        return report

    if plan.intent == "count":
        define_variables(sorted({f["variable"] for f in plan.filters}), trace)
        result = tool("count_respondents", trace, filters=plan.filters, group_by=plan.group_by)
        if "rows" in result:
            for line in (facts.count_facts(result) if not plan.group_by else
                         [f"{r}" for r in result["rows"][:10]]):
                trace.say(DATA_FACT, line, ["count_respondents"])
        return report

    if plan.intent == "percentage":
        define_variables(sorted(set(outcome_sources(plan.outcome)) | {f["variable"] for f in plan.filters}), trace)
        result = tool("weighted_percentage", trace, outcome=plan.outcome, filters=plan.filters,
                      group_by=plan.group_by)
        if "rows" in result:
            for line in facts.percentage_facts(result, plan.group_by):
                trace.say(DATA_FACT, line, ["weighted_percentage"])
            if "indicator" in plan.outcome and "state-module" in DERIVED_BY_NAME[plan.outcome["indicator"]].universe:
                trace.say(CAVEAT, "This question was asked only of women in state-module households "
                                  "(ssmod = 1, about 15% of women), so it rests on that subsample.")
        if wants_profile or plan.needs_outreach:
            report.population = build_profile(plan.filters, trace)
            report.population_reason = "population described in the question"
        return report

    if plan.intent in ("underserved", "outreach_only"):
        if plan.intent == "outreach_only":
            filters = plan.filters or (context_population or {}).get("filters", [])
            report.population = build_profile(filters, trace)
            report.population_reason = "population from the question or the previous answer"
            trace.say(DATA_FACT, f"Target population: {report.population.description}.")
            return report
        return run_underserved(plan, trace, report)

    trace.say(CAVEAT, "The offline router could not identify what to measure. Try naming a characteristic "
                      "(e.g. 'mobile phone', 'health insurance', 'working') and a group, or set "
                      "ANTHROPIC_API_KEY for LLM mode.")
    tool("search_documentation", trace, query=question, k=5)
    return report


def run_underserved(plan, trace, report):
    method = tool("search_documentation", trace, query="what underserved means in this project", k=1)
    if method.get("results"):
        trace.say(DOC_FACT, "Definition used (project methodology): " + method["results"][0]["text"][:700],
                  [method["results"][0]["id"]])
    sources = sorted({v for n in DEFAULT_UNDERSERVED_INDICATORS for v in DERIVED_BY_NAME[n].sources})
    define_variables(sources, trace)

    ranking = tool("rank_underserved_groups", trace, group_by=["v024", "v025"], filters=plan.filters, top_k=10)
    if not ranking.get("rows"):
        trace.say(CAVEAT, "No group met the ranking criteria.")
        return report
    for line in facts.ranking_facts(ranking):
        trace.say(DATA_FACT, line, ["rank_underserved_groups (state x residence)"])
    districts = tool("rank_underserved_groups", trace, group_by=["sdist"], filters=plan.filters, top_k=5)
    if districts.get("rows"):
        trace.say(DATA_FACT, "Most deprived districts (min 200 women): " + "; ".join(
            f"#{r['rank']} {r['group']} {r['deprivation_score']} (n={r['n_women']:,})" for r in districts["rows"]),
            ["rank_underserved_groups (district)"])

    top = ranking["rows"][0]
    filters = [{"variable": "v024", "op": "=", "value": top["v024"]}, {"variable": "v025", "op": "=", "value": top["v025"]}]
    description = f"women aged 15-49 in {top['v025_label']} {top['v024_label'].title()}"
    trace.say(INFERENCE, f"By this project's deprivation score, {description} appear the most underserved "
                         f"state x residence group (score {top['deprivation_score']}). This depends on the "
                         "chosen indicators and equal weighting.", ["rank_underserved_groups"])

    # Sensitivity check: does the conclusion hold for access-based indicators?
    access = tool("rank_underserved_groups", trace, group_by=["v024", "v025"], filters=plan.filters,
                  indicators=["no_mobile_phone", "no_bank_account", "never_used_internet"], top_k=100)
    position = next((r["rank"] for r in access.get("rows", []) if r["group"] == top["group"]), None)
    if position:
        trace.say(DATA_FACT, f"Sensitivity check: on an alternative access-based score (no mobile phone, no bank "
                             f"account, never used internet; state-module subsample), {top['group']} ranks "
                             f"#{position} of {access['n_groups_ranked']} groups.", ["rank_underserved_groups (access)"])
    trace.say(CAVEAT, "No confidence intervals: small differences between groups' scores may not be meaningful.")

    if plan.needs_outreach:
        report.population = build_profile(filters, trace, description)
        report.population_reason = "top-ranked group by deprivation score"
    return report


# ---------------------------------------------------------------------------
# LLM mode
# ---------------------------------------------------------------------------
SYSTEM = f"""You are the Data Agent in a research system about the India NFHS-5 (DHS 2019-21) Individual Recode: 724,115 women aged 15-49.

Use tools for everything:
- Definitions and relevant variables: search_documentation / lookup_variable. Never guess what a variable means from its name.
- Every number: weighted_percentage, count_respondents, age_standardized_rates, rank_underserved_groups, channel_reach, or run_sql. Never compute or estimate numbers yourself.
- Percentages are weighted (w = v005 / 1,000,000). Report unweighted n with them and mention reliability flags.
- Employment, mobile phone, bank and internet questions exist only for state-module women (about 15%); say so when relevant.
- If the task needs a target population for outreach, identify it with tools and then call set_target_population with numeric-code filters.
- Say clearly what is a data result and what is your interpretation. Do not claim causation.

Derived indicators (name: rule): {json.dumps({d.name: d.rule for d in DERIVED_BY_NAME.values()})}
Grouping columns: {json.dumps(GROUPING_COLUMNS)}
Use numeric codes in filters (look up codes with lookup_variable; e.g. v025: 1 urban, 2 rural)."""


def run_llm(task, trace, llm, needs_population=False):
    report = DataReport()

    def set_target_population(trace, description, filters):
        report.population = build_profile(filters, trace, description)
        report.population_reason = "chosen by the Data Agent (LLM)"
        return {"ok": True, "population": report.population.to_dict()}

    tools = DATA_TOOLS + [Tool(
        "set_target_population",
        "Declare the population the outreach research should target (after identifying it with data tools).",
        {"type": "object", "properties": {"description": {"type": "string"},
                                          "filters": DATA_TOOLS_BY_NAME["weighted_percentage"].input_schema["properties"]["filters"]},
         "required": ["description", "filters"]},
        set_target_population, AGENT)]
    by_name = {t.name: t for t in tools}
    prompt = task + ("\n\nThis task needs a target population: finish by calling set_target_population."
                     if needs_population else "")
    messages = [{"role": "user", "content": prompt}]
    response = None
    for _ in range(MAX_TURNS):
        response = llm.create(system=SYSTEM, messages=messages, tools=[t.to_anthropic() for t in tools],
                              purpose="data agent")
        messages.append({"role": "assistant", "content": response.content})
        uses = [b for b in response.content if b.type == "tool_use"]
        if response.stop_reason != "tool_use" or not uses:
            break
        results = []
        for use in uses:
            trace.step(AGENT, "decided", use.name, detail="LLM chose this tool", inputs=use.input)
            output, error = by_name[use.name].run(trace, dict(use.input))
            if not error:
                # Facts come from the tool output (code), not from the model's text.
                for line in facts.facts_for_tool(use.name, output, use.input):
                    trace.say(DATA_FACT, line, [use.name])
            results.append({"type": "tool_result", "tool_use_id": use.id,
                            "content": tool_result_text(output), "is_error": error})
        messages.append({"role": "user", "content": results})
    report.summary = text_of(response) if response is not None else ""
    return report
