"""Turn calculation results into plain-language DATA FACT statements.

These sentences are generated by code from the numbers in a QueryResult, so
they can't contain a number the query didn't produce. Both offline and LLM
modes use them for the "Evidence" section of an answer.
"""


def fmt_pct(value):
    return "suppressed (too few cases)" if value is None else f"{value}%"


def row_label(row, group_by):
    return ", ".join(str(row.get(f"{g}_label")) for g in group_by)


def data_rows(rows):
    """Drop the '(N more rows omitted)' marker rows."""
    return [r for r in rows if "note" not in r]


def percentage_facts(result, group_by, max_groups=6):
    """Statements for a weighted_percentage result."""
    rows = data_rows(result["rows"])
    if not rows:
        return ["No women match this population."]
    lines = []
    if not group_by:
        r = rows[0]
        lines.append(
            f"{fmt_pct(r['weighted_pct'])} of {result['population']}: {result['title'].replace('Weighted % with: ', '')} "
            f"(weighted; n = {r['n_valid']:,} women with a valid answer, {r['n_yes_unweighted']:,} of them 'yes'; "
            f"weighted numerator {r['weighted_numerator']:,} / denominator {r['weighted_denominator']:,}).")
        if r["n_valid"] < r["n_in_population"]:
            lines.append(f"{r['n_in_population'] - r['n_valid']:,} of the {r['n_in_population']:,} women in this "
                         "population have no valid answer (not asked or missing) and are excluded.")
        return lines
    shown = [r for r in rows if r["weighted_pct"] is not None]
    ordered = sorted(shown, key=lambda r: -r["weighted_pct"])
    if len(ordered) > max_groups:
        top, bottom = ordered[:3], ordered[-3:]
        lines.append("Highest: " + "; ".join(f"{row_label(r, group_by)} {r['weighted_pct']}% (n={r['n_valid']:,})" for r in top))
        lines.append("Lowest: " + "; ".join(f"{row_label(r, group_by)} {r['weighted_pct']}% (n={r['n_valid']:,})" for r in bottom))
    else:
        lines.append("; ".join(f"{row_label(r, group_by)}: {r['weighted_pct']}% (n={r['n_valid']:,})" for r in ordered))
    flagged = [r for r in rows if r["reliability"] != "ok"]
    if flagged:
        lines.append(f"{len(flagged)} group(s) have small samples and are suppressed or flagged: "
                     + "; ".join(f"{row_label(r, group_by)} ({r['reliability']})" for r in flagged[:8]))
    return lines


def count_facts(result):
    r = result["rows"][0]
    return [f"{r['n_unweighted']:,} respondents match: {result['population']}. After weighting, they represent "
            f"{r['weighted_pct_of_all_women']}% of all women aged 15-49 in the survey."]


def ranking_facts(result, top=5):
    rows = data_rows(result["rows"])[:top]
    lines = [f"Top {len(rows)} by deprivation score (higher = more women lacking the indicators): "
             + "; ".join(f"#{r['rank']} {r['group']} score {r['deprivation_score']} (n={r['n_women']:,})" for r in rows)]
    if rows:
        best = rows[0]
        parts = [f"{k.replace('pct_', '').replace('_', ' ')} {v}%" for k, v in best.items()
                 if k.startswith("pct_") and v is not None]
        lines.append(f"{best['group']}: " + ", ".join(parts) + ".")
    lines += [n for n in result.get("notes", []) if n.startswith("National reference")]
    return lines


def reach_facts(rows):
    usable = [r for r in rows if r["weighted_pct"] is not None]
    return ["Channel reach in this population: " + "; ".join(
        f"{r['description'].lower()} {r['weighted_pct']}% (n={r['n_valid']:,})" for r in usable) + "."]


def facts_for_tool(name, output, arguments):
    """DATA FACT sentences for one tool call (used in LLM mode)."""
    if name == "weighted_percentage":
        return percentage_facts(output, arguments.get("group_by") or [])
    if name == "count_respondents" and not arguments.get("group_by"):
        return count_facts(output)
    if name == "rank_underserved_groups":
        return ranking_facts(output)
    if name == "channel_reach":
        return reach_facts(output["rows"])
    return []
